# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-12 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Stage_Name', models.CharField(max_length=500)),
                ('Birth_Date', models.CharField(max_length=250)),
                ('Death_Date', models.CharField(max_length=250)),
                ('Primary_Genre', models.CharField(max_length=1000)),
                ('Artist_Bio', models.CharField(max_length=10000)),
                ('Artist_Pic', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Artist'),
        ),
    ]
