from __future__ import unicode_literals

from django.db import models

class Artist(models.Model):
    Name = models.CharField(max_length=500)
    Stage_Name = models.CharField(max_length=250)
    Also_Known_As = models.CharField(max_length=250)
    Band_Members = models.CharField(max_length=500)
    Nationality = models.CharField(max_length=250)
    Birth_Date = models.CharField(max_length=250)
    Death_Date = models.CharField(max_length=250, blank=True)
    Star_Sign = models.CharField(max_length=25, blank=True)
    Currently = models.CharField(max_length=50, blank=True)
    Genre = models.CharField(max_length=1000)
    Bio = models.TextField(max_length=10000, blank=True)
    Artist_Image = models.FileField()
    Official_Website = models.CharField(max_length=500, blank=True)
    Spotify_Link = models.CharField(max_length=500, blank=True)
    Apple_Music = models.CharField(max_length=500, blank=True)
    SoundCloud_Link = models.CharField(max_length=500, blank=True)
    Bandcamp = models.CharField(max_length=500, blank=True)
    Twitter_Link = models.CharField(max_length=500, blank=True)
    Awards = models.CharField(max_length=500, blank=True)
    Contributions = models.CharField(max_length=50, blank=True)
    Personal_Quoute = models.TextField(max_length=1000, blank=True)
    Other_Notes = models.TextField(max_length=100, blank=True)
    Info_Sources = models.CharField(max_length=10000)
    
    
class Album(models.Model):
    Album_Name = models.CharField(max_length=500)
    Album_Image = models.FileField()
    Album_Artist = models.CharField(max_length=500)
    Album_Year = models.CharField(max_length=500)
    Album_Genre = models.CharField(max_length=500)
    Album_Spotify_Link = models.CharField(max_length=500)
    Other_Album_Info = models.TextField(max_length=10000, blank=True)
    Track_1 = models.CharField(max_length=500)
    Track_2 = models.CharField(max_length=500)
    Track_3 = models.CharField(max_length=500)
    Track_4 = models.CharField(max_length=500, blank=True)
    Track_5 = models.CharField(max_length=500, blank=True)
    Track_6 = models.CharField(max_length=500, blank=True)
    Track_7 = models.CharField(max_length=500, blank=True)
    Track_8 = models.CharField(max_length=500, blank=True)
    Track_9 = models.CharField(max_length=500, blank=True)
    Track_10 = models.CharField(max_length=500, blank=True)
    Track_11 = models.CharField(max_length=500, blank=True)
    Track_12 = models.CharField(max_length=500, blank=True)
    Track_13 = models.CharField(max_length=500, blank=True)
    Track_14 = models.CharField(max_length=500, blank=True)
    Track_15 = models.CharField(max_length=500, blank=True)
    Track_16 = models.CharField(max_length=500, blank=True)
    Track_17 = models.CharField(max_length=500, blank=True)
    Track_18 = models.CharField(max_length=500, blank=True)
    Track_19 = models.CharField(max_length=500, blank=True)
    Track_20 = models.CharField(max_length=500, blank=True)
    Contributions = models.CharField(max_length=500, blank=True)
    Awards = models.CharField(max_length=500, blank=True)
    Info_Sources = models.CharField(max_length=10000)
    
class Genres(models.Model):
    Genre_Name = models.CharField(max_length=500)
    Genre_History = models.TextField(max_length=10000, blank=True)
    Latest_Album_Releases = models.TextField(max_length=10000, blank=True)
    Major_Influential_Artists = models.CharField(max_length=500)
    Minor_Influential_Artists = models.CharField(max_length=500, blank=True)
    Info_Sources = models.CharField(max_length=10000)
    
